version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: lydia851/deploysearch-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
      - minio
    

  frontend:
    build:
      context: ./frontend
    image: lydia851/deploysearch-frontend:latest
    expose:
      - "8501"
    environment:
      PYTHONPATH: /app
    depends_on:
      minio:
        condition: service_started
      backend:
        condition: service_started
    

  backend:
    build:
      context: ./backend
    image: lydia851/deploysearch-backend:latest
    expose:
      - "8051"
    environment:
      PYTHONPATH: /app
    depends_on:
      minio:
        condition: service_started
    

  minio:
    build:
      context: ./minio
      dockerfile: dockerfile
    image: lydia851/deploysearch-minio:latest
    command: server /data --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s
    volumes:
      - minio_data:/data
    user: "0:0"
   

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: searchuser
      POSTGRES_PASSWORD: searchpass
      POSTGRES_DB: searchdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose port for local development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U searchuser -d searchdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    

volumes:
  postgres_data:
  minio_data:

networks:
  default:
    name: deploysearch_default